node {
   def registryProjet='/sncf_tp/tp_dev_sncf/db'
   def IMAGE="${registryProjet}:version-${env.BUILD_ID}"
    stage('Clone') {
          checkout scm
    }
    def img = stage('Build') {
          docker.build("$IMAGE",  '.')
    }
    
    stage('Push') {
          docker.withRegistry('', 'dockerhubcredentials') {
              img.push 'latest'
              img.push()
          }
    }
}
